spring:
  profiles:
    active: key
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://testmjuproject.crhbqghbmisx.ap-northeast-2.rds.amazonaws.com/MJU_Project
    username: admin
    password: 12345678
  jwt:
    secret: testsecretkey541@qtgmdkgnrldfdfen
    expiration: 3600000
  elasticsearch:
    host: localhost:9200
    username: elastic
    password: 12345678
  redis:
    host: bill2-redis.tm9um5.ng.0001.apn2.cache.amazonaws.com
    port: 6379

# cors
cors:
  allowed-origins: http://localhost:3000, ec2-3-37-3-225.ap-northeast-2.compute.amazonaws.com, ec2-3-37-34-9.ap-northeast-2.compute.amazonaws.com, Bill2-ELB-Outer-353543633.ap-northeast-2.elb.amazonaws.com, internal-Bill2-ELB-Inner-932056217.ap-northeast-2.elb.amazonaws.com
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: *
  max-age: 3600

photo:
  url:
    default-img: https://bill2market.s3.ap-northeast-2.amazonaws.com/clientPhoto/default-img.png

#Debug
logging:
  level:
    org:
      apache:
        coyote:
          http11: debug